name: Tests

on:
    push:
        branches:
          - 'master'
          - '4.0'
          - '3.1'
          - '3.0'
          - '2.1'
          - '2.0'
          - '1.1'
          - '1.0'
          - '0.9'
    pull_request:
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                php-version: [7.4, 8.1, 8.2, 8.3, 8.4]
        runs-on: ubuntu-22.04
        container:
            image: fsiopenpl/docker-php-apache:alpine-${{ matrix.php-version }}
            env:
                COMPOSER_FLAGS: ${{ matrix.php-version == '7.4' && ' --prefer-lowest' || '' }}
            options: '--network-alias test-container'
        services:
          firefox:
            image: selenium/standalone-firefox:2.53.1
        timeout-minutes: 10
        steps:
            - name: Checkout source
              uses: actions/checkout@v1
            - name: Validate composer config
              run: composer validate
            - name: Install dependencies
              run: composer update ${COMPOSER_FLAGS}
            - name: Install assets
              run: features/fixtures/project/bin/console assets:install features/fixtures/project/web --relative --symlink
            - name: Code quality
              run: composer sniffer
            - name: Code static analysis
              run: composer stan
            - name: Unit tests
              run: composer spec
            - name: Start background processes
              run: |
                nohup php -S 0.0.0.0:8080 -t features/fixtures/project/web > features/fixtures/project/var/logs/server.log 2>&1 &
                sleep 5
            - name: Functional tests
              run: vendor/bin/behat --no-snippets --format=progress --profile=travis -vvv
            - name: Upload logs
              uses: actions/upload-artifact@master
              with:
                name: backend_logs
                path: features/fixtures/project/var/logs
              if: failure()
            - name: Upload debug dumps
              uses: actions/upload-artifact@master
              with:
                name: backend_debug
                path: features/fixtures/project/var/debug
              if: failure()
